# Generated by Django 4.2.5 on 2023-10-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_alter_orderitems_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=40),
        ),
    ]
