# Generated by Django 4.2.5 on 2023-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0006_remove_order_status_orderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
