# Generated by Django 4.2.5 on 2023-10-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0008_razor_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='razor_pay_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
