# Generated by Django 4.2.5 on 2023-10-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0009_orderitems_is_paid_orderitems_razor_pay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='razor_pay_id',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='razor_pay_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
