# Generated by Django 4.2.5 on 2023-10-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0012_wallet_delete_razor_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
