# Generated by Django 4.2.5 on 2023-10-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0015_order_wallet_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_amount',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkouts.coupon'),
        ),
    ]
