# Generated by Django 4.2.5 on 2023-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0016_rename_discount_amount_coupon_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
