# Generated by Django 4.2.5 on 2023-10-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0017_orderitems_amount_to_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
