# Generated by Django 4.2.5 on 2023-10-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0019_remove_coupon_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='discounted_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
