# Generated by Django 4.2.5 on 2023-10-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0020_orderitems_discounted_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='amount_to_pay',
        ),
    ]
