# Generated by Django 4.2.5 on 2023-10-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0023_coupon_maximum_use_coupon_minimum_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponhistory',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='checkouts.coupon'),
        ),
    ]
