# Generated by Django 4.2.5 on 2023-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0025_order_city_order_district_order_local_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
