# Generated by Django 4.2.5 on 2023-09-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='https://i.imgur.com/KEVc5ox.jpg', null=True),
        ),
    ]
