# Generated by Django 4.2.5 on 2023-09-18 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
