# Generated by Django 4.2.5 on 2023-09-18 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_forgot_password_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
