# Generated by Django 4.2.5 on 2023-09-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_otp_profile_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_verified',
        ),
    ]
