# Generated by Django 4.2.5 on 2023-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_email_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='https://i.imgur.com/KEVc5ox.jpg', null=True, upload_to='profile'),
        ),
    ]
