# Generated by Django 4.2.5 on 2023-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hexcode',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
