# Generated by Django 4.2.5 on 2023-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_hexcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexcode',
            field=models.CharField(max_length=50),
        ),
    ]
