# Generated by Django 4.2.5 on 2023-09-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_color_hexcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='image_down',
            new_name='image_side',
        ),
        migrations.RenameField(
            model_name='product_image',
            old_name='image_left',
            new_name='image_up',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='image_right',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='inside_image',
        ),
        migrations.AddField(
            model_name='brand',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='size',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
