# Generated by Django 4.2.5 on 2023-09-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_down_product_image_image_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_enlarged_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_side', models.CharField(blank=True, max_length=255, null=True)),
                ('image_back', models.CharField(blank=True, max_length=255, null=True)),
                ('image_up', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
