# Generated by Django 4.2.5 on 2023-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_enlarged_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='big_image_back',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_image',
            name='big_image_side',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_image',
            name='big_image_up',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Product_enlarged_image',
        ),
    ]
