# Generated by Django 4.2.5 on 2023-09-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_big_image_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='big_image_back',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='big_image_side',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='big_image_up',
        ),
    ]
