# Generated by Django 4.2.5 on 2023-09-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_image_big_image_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unlisted',
        ),
    ]
