# Generated by Django 4.2.5 on 2023-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_back',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_side',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_up',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
