# Generated by Django 4.2.5 on 2023-10-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_size_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='unlisted',
        ),
    ]
