# Generated by Django 4.2.5 on 2023-10-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_cartitems_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
