# Generated by Django 4.2.5 on 2023-10-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_cart_total_price_remove_cartitems_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
