# Generated by Django 4.2.5 on 2023-10-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
