# Generated by Django 4.2.5 on 2023-10-14 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
