# Generated by Django 4.2.5 on 2023-10-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_banner_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banncer_image',
            field=models.ImageField(upload_to='banner'),
        ),
    ]
