# Generated by Django 4.2.5 on 2023-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_rename_banncer_image_banner_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
