# Generated by Django 4.2.5 on 2023-10-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_categoryoffer_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
